x = input("Wprowadz pierwsza liczbe: ")
y = input("Wprowadz druga liczba: ")
z = input("Wprowadz trzecia liczbe: ")
c = (x,y,z)

s = sorted(c)
print("Posortowane: ",sorted(c))
print("Suma: ",(x+y+z))
print("Min: ",min(c))
print("Max: ",max(c))
